[package]
name = "askama"
version = "0.3.4"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
readme = "../README.md"

[badges]
travis-ci = { repository = "djc/askama" }

[features]
iron = ["askama_iron"]

[dependencies]
askama_derive = { path = "../askama_derive", version = "0.3.4" }
error-chain = "0.10"
askama_iron = { path = "../askama_iron", version = "0.1", optional = true }
